export default [
    {value: 'AF', viewValue: 'Afeganistão'},
    {value: 'ZA', viewValue: 'Africa do Sul'},
    {value: 'AL', viewValue: 'Albânia'},
    {value: 'DE', viewValue: 'Alemanha'},
    {value: 'AD', viewValue: 'Andorra'},
    {value: 'AO', viewValue: 'Angola'},
    {value: 'AI', viewValue: 'Anguilla'},
    {value: 'AQ', viewValue: 'Antartica'},
    {value: 'AG', viewValue: 'Antígua e Barbuda'},
    {value: 'AN', viewValue: 'Antilhas Holandesas'},
    {value: 'SA', viewValue: 'Arábia Saudita'},
    {value: 'DZ', viewValue: 'Argélia'},
    {value: 'AR', viewValue: 'Argentina'},
    {value: 'AM', viewValue: 'Armênia'},
    {value: 'AW', viewValue: 'Aruba'},
    {value: 'AU', viewValue: 'Austrália'},
    {value: 'AT', viewValue: 'Áustria'},
    {value: 'AZ', viewValue: 'Azerbaidjão'},
    {value: 'BS', viewValue: 'Bahamas'},
    {value: 'BD', viewValue: 'Bangladesh'},
    {value: 'BB', viewValue: 'Barbados'},
    {value: 'BH', viewValue: 'Bareine'},
    {value: 'BY', viewValue: 'Belarus'},
    {value: 'BE', viewValue: 'Bélgica'},
    {value: 'BZ', viewValue: 'Belize'},
    {value: 'BX', viewValue: 'Benelux'},
    {value: 'BJ', viewValue: 'Benin'},
    {value: 'BM', viewValue: 'Bermudas'},
    {value: 'BO', viewValue: 'Bolívia'},
    {value: 'BA', viewValue: 'Bósnia e Herzegóvina'},
    {value: 'BW', viewValue: 'Botswana'},
    {value: 'BR', viewValue: 'Brasil'},
    {value: 'BG', viewValue: 'Bulgária'},
    {value: 'BN', viewValue: 'Brunei Darussalam'},
    {value: 'BF', viewValue: 'Burkina Faso'},
    {value: 'BI', viewValue: 'Burundi'},
    {value: 'BT', viewValue: 'Butão'},
    {value: 'CV', viewValue: 'Cabo Verde'},
    {value: 'CM', viewValue: 'Camarões'},
    {value: 'KH', viewValue: 'Camboja'},
    {value: 'CA', viewValue: 'Canadá'},
    {value: 'QA', viewValue: 'Catar'},
    {value: 'KZ', viewValue: 'Cazaquistão'},
    {value: 'TD', viewValue: 'Chade'},
    {value: 'GW', viewValue: 'Guiné Bissau'},
    {value: 'GQ', viewValue: 'Guine Equatorial'},
    {value: 'HT', viewValue: 'Haiti'},
    {value: 'NL', viewValue: 'Holanda'},
    {value: 'HN', viewValue: 'Honduras'},
    {value: 'HK', viewValue: 'Hong-Kong'},
    {value: 'HU', viewValue: 'Hungria'},
    {value: 'YE', viewValue: 'Iêmen'},
    {value: 'BV', viewValue: 'Ilha Bouvet'},
    {value: 'IM', viewValue: 'Ilha do Homem'},
    {value: 'CX', viewValue: 'Ilha Natal'},
    {value: 'NF', viewValue: 'Ilha Norfalk'},
    {value: 'KY', viewValue: 'Ilhas Cayman'},
    {value: 'CC', viewValue: 'Ilhas Cocos'},
    {value: 'CK', viewValue: 'Ilhas Cook'},
    {value: 'GG', viewValue: 'Ilhas do Canal'},
    {value: 'FO', viewValue: 'Ilhas Faroe'},
    {value: 'HM', viewValue: 'Ilhas Heard e McDonald'},
    {value: 'FK', viewValue: 'Ilhas Malvinas'},
    {value: 'MP', viewValue: 'Ilhas Marianas do Norte'},
    {value: 'MH', viewValue: 'Ilhas Marshall'},
    {value: 'UM', viewValue: 'Ilhas Menores'},
    {value: 'SB', viewValue: 'Ilhas Salomão'},
    {value: 'TC', viewValue: 'Ilhas Turks e Caicos'},
    {value: 'VG', viewValue: 'Ilhas Virgens (Britânicas)'},
    {value: 'VI', viewValue: 'Ilhas Virgens (U.S.)'},
    {value: 'WF', viewValue: 'Ilhas Wallis e Futura'},
    {value: 'IN', viewValue: 'India'},
    {value: 'ID', viewValue: 'Indonésia'},
    {value: 'IR', viewValue: 'Irã'},
    {value: 'IQ', viewValue: 'Iraque'},
    {value: 'IE', viewValue: 'Irlanda'},
    {value: 'IS', viewValue: 'Islândia'},
    {value: 'IL', viewValue: 'Israel'},
    {value: 'ID', viewValue: 'Indonésia'},
    {value: 'IR', viewValue: 'Irã'},
    {value: 'IQ', viewValue: 'Iraque'},
    {value: 'IE', viewValue: 'Irlanda'},
    {value: 'IS', viewValue: 'Islândia'},
    {value: 'IL', viewValue: 'Israel'},
    {value: 'IT', viewValue: 'Itália'},
    {value: 'JM', viewValue: 'Jamaica'},
    {value: 'JP', viewValue: 'Japão'},
    {value: 'JE', viewValue: 'Jersey'},
    {value: 'PW', viewValue: 'Palau'},
    {value: 'PA', viewValue: 'Panamá'},
    {value: 'PG', viewValue: 'Papua Nova Guiné'},
    {value: 'PK', viewValue: 'Paquistão'},
    {value: 'PY', viewValue: 'Paraguai'},
    {value: 'PE', viewValue: 'Peru'},
    {value: 'PN', viewValue: 'Pitcairn'},
    {value: 'PF', viewValue: 'Polinésia Francesa'},
    {value: 'PL', viewValue: 'Polônia'},
    {value: 'PR', viewValue: 'Porto Rico'},
    {value: 'PT', viewValue: 'Portugal'},
    {value: 'KE', viewValue: 'Quênia'},
    {value: 'KG', viewValue: 'Quirguistão'},
    {value: 'GB', viewValue: 'Reino Unido'},
    {value: 'CF', viewValue: 'República Centro Africana'},
    {value: 'KR', viewValue: 'República da Coréia'},
    {value: 'MK', viewValue: 'República da Macedonia'},
    {value: 'MD', viewValue: 'República da Moldova'},
    {value: 'CD', viewValue: 'República Dem. Do Congo'},
    {value: 'DO', viewValue: 'República Dominicana'},
    {value: 'KP', viewValue: 'República Pop. Dem. da Coreia'},
    {value: 'CZ', viewValue: 'República Tcheca'},
    {value: 'TZ', viewValue: 'República Unida da Tanzânia'},
    {value: 'RE', viewValue: 'Reunião'},
    {value: 'RO', viewValue: 'Romênia'},
    {value: 'RW', viewValue: 'Ruanda'},
    {value: 'EH', viewValue: 'Saara Ocidental'},
    {value: 'PM', viewValue: 'Saint Pierre e Miquelon'},
    {value: 'AS', viewValue: 'Samoa Americana'},
    {value: 'WS', viewValue: 'Samoa Ocidental'},
    {value: 'SH', viewValue: 'Santa Helena'},
    {value: 'LC', viewValue: 'Santa Lúcia'},
    {value: 'SM', viewValue: 'São Marino'},
    {value: 'VC', viewValue: 'São Vicente e Granadinas'},
    {value: 'SL', viewValue: 'Serra Leoa'},
    {value: 'SC', viewValue: 'Seychelles'},
    {value: 'SY', viewValue: 'Síria'},
    {value: 'LK', viewValue: 'Sri Lanka'},
    {value: 'SD', viewValue: 'Sudão'},
    {value: 'CL', viewValue: 'Chile'},
    {value: 'CN', viewValue: 'China'},
    {value: 'CY', viewValue: 'Chipre'},
    {value: 'CO', viewValue: 'Colômbia'},
    {value: 'KM', viewValue: 'Comores'},
    {value: 'CG', viewValue: 'Congo'},
    {value: 'CI', viewValue: 'Costa do Marfim'},
    {value: 'CR', viewValue: 'Costa Rica'},
    {value: 'HR', viewValue: 'Croácia'},
    {value: 'CU', viewValue: 'Cuba'},
    {value: 'DK', viewValue: 'Dinamarca'},
    {value: 'DJ', viewValue: 'Djibuti'},
    {value: 'DM', viewValue: 'Dominica'},
    {value: 'EG', viewValue: 'Egito'},
    {value: 'SV', viewValue: 'El Salvador'},
    {value: 'AE', viewValue: 'Emirados Árabes Unidos'},
    {value: 'EC', viewValue: 'Equador'},
    {value: 'ER', viewValue: 'Eritréia'},
    {value: 'EM', viewValue: 'Escritório para Harmonização no Mercado Interno'},
    {value: 'SK', viewValue: 'Eslováquia'},
    {value: 'SI', viewValue: 'Eslovenia'},
    {value: 'ES', viewValue: 'Espanha'},
    {value: 'US', viewValue: 'Estados Unidos da América'},
    {value: 'EE', viewValue: 'Estônia'},
    {value: 'ET', viewValue: 'Etiópia'},
    {value: 'RU', viewValue: 'Federação Russa'},
    {value: 'FJ', viewValue: 'Fiji'},
    {value: 'PH', viewValue: 'Filipinas'},
    {value: 'FI', viewValue: 'Finlândia'},
    {value: 'FR', viewValue: 'França'},
    {value: 'GA', viewValue: 'Gabão'},
    {value: 'GM', viewValue: 'Gambia'},
    {value: 'GE', viewValue: 'Geórgia'},
    {value: 'GH', viewValue: 'Gana'},
    {value: 'GS', viewValue: 'Geórgia do Sul e Ilhas Sandwich do Sul'},
    {value: 'GI', viewValue: 'Gibraltar'},
    {value: 'GD', viewValue: 'Granada'},
    {value: 'GR', viewValue: 'Grécia'},
    {value: 'GL', viewValue: 'Groenlândia'},
    {value: 'GP', viewValue: 'Guadalupe'},
    {value: 'GU', viewValue: 'Guam'},
    {value: 'GT', viewValue: 'Guatemala'},
    {value: 'GY', viewValue: 'Guiana'},
    {value: 'GN', viewValue: 'Guine'},
    {value: 'JO', viewValue: 'Jordânia'},
    {value: 'KI', viewValue: 'Kiribati'},
    {value: 'KW', viewValue: 'Kuwait'},
    {value: 'LA', viewValue: 'Laos'},
    {value: 'LS', viewValue: 'Lesoto'},
    {value: 'LV', viewValue: 'Letônia'},
    {value: 'LB', viewValue: 'Líbano'},
    {value: 'LR', viewValue: 'Libéria'},
    {value: 'LY', viewValue: 'Líbia'},
    {value: 'LI', viewValue: 'Liechtenstein'},
    {value: 'LT', viewValue: 'Lituânia'},
    {value: 'LU', viewValue: 'Luxemburgo'},
    {value: 'MO', viewValue: 'Macau'},
    {value: 'MG', viewValue: 'Madagascar'},
    {value: 'MY', viewValue: 'Malásia'},
    {value: 'MW', viewValue: 'Malawi'},
    {value: 'MV', viewValue: 'Maldivas'},
    {value: 'ML', viewValue: 'Mali'},
    {value: 'MT', viewValue: 'Malta'},
    {value: 'MA', viewValue: 'Marrocos'},
    {value: 'MQ', viewValue: 'Martinica'},
    {value: 'MU', viewValue: 'Maurício'},
    {value: 'MR', viewValue: 'Mauritânia'},
    {value: 'MX', viewValue: 'México'},
    {value: 'MM', viewValue: 'Mianmá'},
    {value: 'FM', viewValue: 'Micronésia'},
    {value: 'MZ', viewValue: 'Moçambique'},
    {value: 'MC', viewValue: 'Mônaco'},
    {value: 'MN', viewValue: 'Mongólia'},
    {value: 'MS', viewValue: 'Mont Serrat'},
    {value: 'ME', viewValue: 'Montenegro'},
    {value: 'NA', viewValue: 'Namíbia'},
    {value: 'NR', viewValue: 'Nauru'},
    {value: 'NP', viewValue: 'Nepal'},
    {value: 'NI', viewValue: 'Nicarágua'},
    {value: 'NE', viewValue: 'Níger'},
    {value: 'NG', viewValue: 'Nigéria'},
    {value: 'NO', viewValue: 'Noruega'},
    {value: 'NC', viewValue: 'Nova Caledônia'},
    {value: 'NZ', viewValue: 'Nova Zelândia'},
    {value: 'OM', viewValue: 'Omã'},
    {value: 'OA', viewValue: 'Organização Africana de Propriedade Intelectual (OAPI)'},
    {value: 'WO', viewValue: 'Organização Mundial de Propriedade Intelectual – OMPI (WIPO)'},
    {value: 'AP', viewValue: 'Organização Regional de Propriedade Industrial Africana'},
    {value: 'SE', viewValue: 'Suécia'},
    {value: 'CH', viewValue: 'Suíça'},
    {value: 'SR', viewValue: 'Suriname'},
    {value: 'SJ', viewValue: 'Svalbard e Jan Mayen'},
    {value: 'TJ', viewValue: 'Tadjiquistão'},
    {value: 'TH', viewValue: 'Tailândia'},
    {value: 'TW', viewValue: 'Taiwan'},
    {value: 'TF', viewValue: 'Terras Austrais Francesas'},
    {value: 'IO', viewValue: 'Territ.Britan.Oceano Índico'},
    {value: 'PS', viewValue: 'Território Ocupado Palestino'},
    {value: 'TL', viewValue: 'Timor-Leste'},
    {value: 'TG', viewValue: 'Togo'},
    {value: 'TK', viewValue: 'Tokelau'},
    {value: 'TO', viewValue: 'Tonga'},
    {value: 'TT', viewValue: 'Trinidad e Tobago'},
    {value: 'TN', viewValue: 'Tunísia'},
    {value: 'TM', viewValue: 'Turcomenistão'},
    {value: 'TR', viewValue: 'Turquia'},
    {value: 'TV', viewValue: 'Tuvalu'},
    {value: 'UA', viewValue: 'Ucrânia'},
    {value: 'UG', viewValue: 'Uganda'},
    {value: 'UY', viewValue: 'Uruguai'},
    {value: 'UZ', viewValue: 'Uzbequistão'},
    {value: 'VU', viewValue: 'Vanuatu'},
    {value: 'VA', viewValue: 'Vaticano'},
    {value: 'VE', viewValue: 'Venezuela'},
    {value: 'VN', viewValue: 'Vietnã'},
    {value: 'YU', viewValue: 'Yugoslávia'},
    {value: 'ZR', viewValue: 'Zaire'},
    {value: 'ZM', viewValue: 'Zâmbia'},
    {value: 'ZW', viewValue: 'Zimbábue'},
    {value: 'KN', viewValue: 'São Cristovão e Nevis'},
    {value: 'ST', viewValue: 'São Tomé e Príncipe'},
    {value: 'SN', viewValue: 'Senegal'},
    {value: 'RS', viewValue: 'Sérvia'},
    {value: 'SG', viewValue: 'Singapura'},
    {value: 'SO', viewValue: 'Somália'},
    {value: 'SZ', viewValue: 'Suazilândia'}
]